// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {
  let n1 = 1;
  let n2 = n1;
  let evenSum = 0;
  for (let i = 0; i < n; i++) {
    let sum = n1 + n2;
    if (sum > n) {
      break;
    } else if (sum % 2 === 0) {
      evenSum += sum;
    }
    n1 = n2;
    n2 = sum;
  }
  return evenSum;
}

console.log(fiboEvenSum(10));
